kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.deployment.repository }}:{{ .Values.name }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy | default "Never" }}
          ports:
            - containerPort: {{ .Values.deployment.port | default 80 }}

          resources: {{- toYaml .Values.resources | nindent 12 }}
