{{- $name := .Values.name -}}
{{- $port := .Values.deployment.port | default 80 -}}


kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    spec:
      containers:
        - name: {{ $name }}
          image: {{ .Values.deployment.repository }}:{{ .Values.deployment.tag }}
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy | default "Never" }}
          ports:
            - containerPort: {{ $port }}

          resources: {{- toYaml .Values.resources | nindent 12 }}
